# Set theme
# theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://pandolia.net'
baseurl: ''
title: "Pandolia 的博客"
description: 'Pandolia 的博客'
permalink: pretty
date_format: '%Y-%m-%d'
logo: '/logo.png'
excerpt_separator: <!--more-->
lang: zh-CN

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  主页: /
  分类: /categories/
  链接: /links/
  # github: https://github.com/pandolia/
  # tinyc: https://pandolia.net/tinyc/

# Footer nav
navigation_footer:
  返回顶部: '#top'

# Collections
collections:
  posts:
    output: true
    feature_image: '/image/872.jpg'
