# Jekyll configuration

name: Pandolia's blog

description: It is written

#author global variable
author:
    name: Pandolia
    email: pandolia@yeah.net

# url is currently only used only for the RSS feed in feed.xml
url: 'http://pandolia.net/'

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or duoshuo below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your duoshuo shortname to enable comments via duoshuo. Set to '' to disable duoshuo.
duoshuo: 'pandolia'

permalink: /:year/:month/:title
paginate: 5

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']

excerpt_separator: <!--more-->
