# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pandolia的博客
email: pandolia@yeah.net
description: > # this means to ignore newlines until "baseurl:"
  Pandolia的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pandolia.github.io" # the base hostname & protocol for your site
github_username:  pandolia

# Build settings
markdown: kramdown

# customer global variable
jianshu: "http://www.jianshu.com/users/46fd9a28f80c/latest_articles"
sourcecode: "https://github.com/pandolia/pandolia.github.io"
