# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pandolia的博客
description: > # this means to ignore newlines until "baseurl:"
  编程 算法 汇编 静态博客
baseurl:  # the subpath of your site, e.g. /blog
github_username:  pandolia
include: ["/test/_x/bbb.png"]

# customer global variable
navigation:
- text: 主页
  url: /
- text: 书签
  url: /bookmark.html
- text: TinyC
  url: /tinyc
- text: 简书
  url: http://www.jianshu.com/users/46fd9a28f80c/latest_articles
- text: 本站源码
  url: https://github.com/pandolia/pandolia.github.io
